/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './src/app/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
    './src/pages/**/*.{js,jsx,ts,tsx}',
  ],
  plugins: [],
  theme: {
    extend: {
      backgroundColor: {
        'accent': 'rgb(var(--background-accent))',
        'accent-hover': 'rgb(var(--background-accent-hover))',
        'accent-secondary': 'rgb(var(--background-accent-secondary))',
        'accent-secondary-hover': 'rgb(var(--background-accent-secondary-hover))',
        'danger': 'rgb(var(--background-danger))',
        'danger-hover': 'rgb(var(--background-danger-hover))',
        'invert': 'rgb(var(--background-invert))',
        'invert-hover': 'rgb(var(--background-invert-hover))',
        'primary': 'rgb(var(--background-primary))',
        'primary-hover': 'rgb(var(--background-primary-hover))',
        'secondary': 'rgb(var(--background-secondary))',
        'secondary-hover': 'rgb(var(--background-secondary-hover))',
        'tertiary': 'rgb(var(--background-tertiary))',
        'tertiary-hover': 'rgb(var(--background-tertiary-hover))',
      },
      borderColor: {
        'accent': 'rgb(var(--border-accent))',
        'accent-hover': 'rgb(var(--border-accent-hover))',
        'accent-secondary': 'rgb(var(--border-accent-secondary))',
        'accent-secondary-hover': 'rgb(var(--border-accent-secondary-hover))',
        'danger': 'rgb(var(--border-danger))',
        'danger-hover': 'rgb(var(--border-danger-hover))',
        'invert': 'rgb(var(--border-invert))',
        'invert-hover': 'rgb(var(--border-invert-hover))',
        'primary': 'rgb(var(--border-primary))',
        'primary-hover': 'rgb(var(--border-primary-hover))',
        'secondary': 'rgb(var(--border-secondary))',
        'secondary-hover': 'rgb(var(--border-secondary-hover))',
        'tertiary': 'rgb(var(--border-tertiary))',
        'tertiary-hover': 'rgb(var(--border-tertiary-hover))',
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'noto': ['Noto Sans', 'sans-serif'],
      },
      fontSize: {
        '2xs': '.625rem', 
        '3xs': '.5rem'
      },
      height: {'120': '30rem'},
      outlineColor: {
        'accent': 'rgb(var(--border-accent))',
        'accent-hover': 'rgb(var(--border-accent-hover))',
        'accent-secondary': 'rgb(var(--border-accent-secondary))',
        'accent-secondary-hover': 'rgb(var(--border-accent-secondary-hover))',
        'danger': 'rgb(var(--border-danger))',
        'danger-hover': 'rgb(var(--border-danger-hover))',
        'invert': 'rgb(var(--border-invert))',
        'invert-hover': 'rgb(var(--border-invert-hover))',
        'primary': 'rgb(var(--border-primary))',
        'primary-hover': 'rgb(var(--border-primary-hover))',
        'secondary': 'rgb(var(--border-secondary))',
        'secondary-hover': 'rgb(var(--border-secondary-hover))',
        'tertiary': 'rgb(var(--border-tertiary))',
        'tertiary-hover': 'rgb(var(--border-tertiary-hover))',
      },
      screens: {
        'xs': '375px',
      },
      textColor: {
        'accent': 'rgb(var(--text-accent))',
        'accent-hover': 'rgb(var(--text-accent-hover))',
        'accent-secondary': 'rgb(var(--text-accent-secondary))',
        'accent-secondary-hover': 'rgb(var(--text-accent-secondary-hover))',
        'danger': 'rgb(var(--text-danger))',
        'danger-hover': 'rgb(var(--text-danger-hover))',
        'invert': 'rgb(var(--text-invert))',
        'invert-hover': 'rgb(var(--text-invert-hover))',
        'primary': 'rgb(var(--text-primary))',
        'primary-hover': 'rgb(var(--text-primary-hover))',
        'secondary': 'rgb(var(--text-secondary))',
        'secondary-hover': 'rgb(var(--text-secondary-hover))',
        'tertiary': 'rgb(var(--text-tertiary))',
        'tertiary-hover': 'rgb(var(--text-tertiary-hover))',
      },
      width: {
        '120': '30rem',
        '150': '37.5rem',
        '180': '45rem',
        '210': '52.5rem',
        '240': '60rem',
        '270': '67.5rem',
        '300': '75rem',
        '330': '82.5rem',
        '360': '90rem'
      },
    },
  },
};
